/* MSC v8 text-based PDF calendar import */
(() => {
  'use strict';
  const VERSION='5.7.284',BASE=`https://cdn.jsdelivr.net/npm/pdfjs-dist@${VERSION}/build/`;let pdfjsPromise=null;
  async function loadPdfJs(){if(pdfjsPromise)return pdfjsPromise;pdfjsPromise=import(`${BASE}pdf.min.mjs`).then(m=>{m.GlobalWorkerOptions.workerSrc=`${BASE}pdf.worker.min.mjs`;return m;});return pdfjsPromise;}
  const monthIndex=n=>['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].findIndex(m=>n.toLowerCase().startsWith(m));
  function parseText(text){const lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean),out=[],year=new Date().getFullYear(),patterns=[/\b(20\d{2})[-\/]([01]?\d)[-\/]([0-3]?\d)\b/,/\b([0-3]?\d)[\/]([01]?\d)[\/](20\d{2})\b/,/\b(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+([0-3]?\d)(?:,\s*(20\d{2}))?/i,/\b([0-3]?\d)\s+(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)(?:\s+(20\d{2}))?/i];for(const line of lines){let d=null,m=null,confidence='medium';if((m=line.match(patterns[0])))d=new Date(+m[1],+m[2]-1,+m[3]);else if((m=line.match(patterns[1])))d=new Date(+m[3],+m[2]-1,+m[1]);else if((m=line.match(patterns[2])))d=new Date(+(m[3]||year),monthIndex(m[1]),+m[2]);else if((m=line.match(patterns[3])))d=new Date(+(m[3]||year),monthIndex(m[2]),+m[1]);if(!d||Number.isNaN(+d))continue;let title=line.replace(m[0],'').replace(/^[-–—:|\s]+|[-–—:|\s]+$/g,'').trim();if(title.length<3)continue;if(title.length>110)title=title.slice(0,110);if(/^(mon|tue|wed|thu|fri|sat|sun)/i.test(title))confidence='low';const start=new Date(d),end=new Date(d);start.setHours(8,0,0,0);end.setHours(15,0,0,0);out.push({...fresh(title),start:start.toISOString(),end:end.toISOString(),source:'pdf',pdfConfidence:confidence});}const seen=new Set();return out.filter(e=>{const k=`${e.name.toLowerCase()}|${e.start.slice(0,10)}`;if(seen.has(k))return false;seen.add(k);return true;}).slice(0,250);}
  async function parsePdf(file){const pdfjs=await loadPdfJs(),data=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjs.getDocument({data}).promise,lines=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent(),items=content.items.map(i=>({str:i.str,x:i.transform?.[4]||0,y:i.transform?.[5]||0})).sort((a,b)=>Math.abs(b.y-a.y)>3?b.y-a.y:a.x-b.x);let line='',lastY=null;for(const it of items){if(lastY!==null&&Math.abs(it.y-lastY)>3){if(line.trim())lines.push(line.trim());line='';}line+=(line?' ':'')+it.str;lastY=it.y;}if(line.trim())lines.push(line.trim());}return parseText(lines.join('\n'));}
  const baseLoadImport=typeof loadImport==='function'?loadImport:null;if(baseLoadImport)loadImport=async function(file){if(!file.name.toLowerCase().endsWith('.pdf'))return baseLoadImport(file);try{$('#importPreview').innerHTML='<div class="pdf-import-summary"><strong>Reading PDF calendar…</strong> Text-based calendars work best; scanned/image-only PDFs are not OCRed.</div>';imports=await parsePdf(file);$('#importPreview').innerHTML=`<div class="pdf-import-summary"><strong>${imports.length} possible calendar item${imports.length===1?'':'s'} found.</strong> Review before importing; PDF layouts vary, so extracted dates are suggestions.</div>`+(imports.map((e,i)=>`<label class="import-row"><input type="checkbox" data-import-index="${i}" checked><strong>${esc(e.name)}</strong><span class="pdf-confidence">${esc(e.pdfConfidence||'medium')}</span><span style="margin-left:auto;color:#777">${fmtDate(e.start)}</span></label>`).join('')||'<div class="empty-state">No dated calendar entries detected.</div>');$('#confirmImportButton').disabled=!imports.length;}catch(err){console.error(err);toast('Could not read that PDF calendar');$('#importPreview').innerHTML='<div class="empty-state">This PDF could not be parsed. Text-based PDFs are supported; scanned PDFs need OCR.</div>';}};
  const input=document.getElementById('calendarFile');if(input)input.accept='.ics,.ical,.json,.pdf,application/pdf';const small=document.querySelector('#dropZone small');if(small)small.textContent='Supports .ics / .ical, JSON and text-based PDF calendars';
})();
